"""Alembic migration environment.

Migrations run synchronously via psycopg3 (the app itself uses asyncpg); the URL
is derived from settings, with an ALEMBIC_URL override so the baseline can be
autogenerated against an empty scratch DB. `import app.models` registers every
table on Base.metadata so autogenerate sees the full schema.
"""
import os

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

import app.models  # noqa: F401  — registers all tables on Base.metadata
from app.core.config import settings
from app.core.db import Base

config = context.config

# Migrations use a SYNC driver (psycopg3). ALEMBIC_URL lets us point at a scratch
# DB for autogenerate without touching the live one.
sync_url = os.environ.get("ALEMBIC_URL") or settings.database_url.replace(
    "+asyncpg", "+psycopg"
)
config.set_main_option("sqlalchemy.url", sync_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    context.configure(
        url=sync_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
