"""baseline

Revision ID: abb6aa863be3
Revises: 
Create Date: 2026-06-12 03:36:03.351483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector  # the Chunk.embedding column type


# revision identifiers, used by Alembic.
revision: str = 'abb6aa863be3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector extension must exist before the chunks.embedding VECTOR column.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('reader', 'contributor', 'editor', 'admin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mcp_enabled', sa.Boolean(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('is_agent', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_owner_id'), 'users', ['owner_id'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('is_bundle', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_owner_id'), 'artifacts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_artifacts_short_id'), 'artifacts', ['short_id'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_target_id'), 'audit_log', ['target_id'], unique=False)
    op.create_table('category_editors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'user_id', name='uq_cat_editor')
    )
    op.create_index(op.f('ix_category_editors_category_id'), 'category_editors', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_editors_user_id'), 'category_editors', ['user_id'], unique=False)
    op.create_table('lint_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('planning', 'done', 'failed', name='lintreportstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('provider_model', sa.String(), nullable=True),
    sa.Column('retrieval_strategy', sa.String(), nullable=True),
    sa.Column('total_issues', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lint_reports_status'), 'lint_reports', ['status'], unique=False)
    op.create_index(op.f('ix_lint_reports_triggered_by_id'), 'lint_reports', ['triggered_by_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Enum('open', 'stable', 'locked', name='pagestability'), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='pagestatus'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('current_revision_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_revision_id'], ['revisions.id'], name='fk_pages_current_rev', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_category_id'), 'pages', ['category_id'], unique=False)
    op.create_index(op.f('ix_pages_path'), 'pages', ['path'], unique=True)
    op.create_table('raw_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('disk_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('ingest_status', sa.Enum('pending', 'ingesting', 'done', 'failed', name='ingeststatus'), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ingest_notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disk_filename')
    )
    op.create_index(op.f('ix_raw_sources_ingest_status'), 'raw_sources', ['ingest_status'], unique=False)
    op.create_index(op.f('ix_raw_sources_title'), 'raw_sources', ['title'], unique=False)
    op.create_index(op.f('ix_raw_sources_uploaded_by_id'), 'raw_sources', ['uploaded_by_id'], unique=False)
    op.create_table('artifact_access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_access_log_accessed_at'), 'artifact_access_log', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_artifact_access_log_artifact_id'), 'artifact_access_log', ['artifact_id'], unique=False)
    op.create_table('artifact_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('body_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'version', name='uq_artifact_version')
    )
    op.create_index(op.f('ix_artifact_versions_artifact_id'), 'artifact_versions', ['artifact_id'], unique=False)
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'page_id', name='uq_bookmark_user_page')
    )
    op.create_index(op.f('ix_bookmarks_page_id'), 'bookmarks', ['page_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_type', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_page_id'), 'chunks', ['page_id'], unique=False)
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('incorrect', 'outdated', 'needs_source', 'duplicate', 'other', name='flagkind'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', name='flagstatus'), nullable=False),
    sa.Column('raised_by_id', sa.Integer(), nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_page_id'), 'flags', ['page_id'], unique=False)
    op.create_index(op.f('ix_flags_status'), 'flags', ['status'], unique=False)
    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_source_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('agent_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('planning', 'pending_review', 'applying', 'done', 'dismissed', 'superseded', 'failed', 'partially_failed', name='ingestrunstatus'), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=True),
    sa.Column('approved_edit_indices', sa.JSON(), nullable=True),
    sa.Column('retrieval_strategy', sa.String(), nullable=True),
    sa.Column('provider_model', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('edits_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('conflict_count', sa.Integer(), nullable=False),
    sa.Column('applied_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_source_id'], ['raw_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_runs_raw_source_id'), 'ingest_runs', ['raw_source_id'], unique=False)
    op.create_index(op.f('ix_ingest_runs_status'), 'ingest_runs', ['status'], unique=False)
    op.create_index(op.f('ix_ingest_runs_triggered_by_id'), 'ingest_runs', ['triggered_by_id'], unique=False)
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_path', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_path', name='uq_link')
    )
    op.create_index(op.f('ix_links_source_id'), 'links', ['source_id'], unique=False)
    op.create_index(op.f('ix_links_target_id'), 'links', ['target_id'], unique=False)
    op.create_index(op.f('ix_links_target_path'), 'links', ['target_path'], unique=False)
    op.create_table('lint_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('orphan', 'broken_link', 'conflict', 'stale', 'source_drift', 'other', name='lintissuekind'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='lintissueseverity'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affected_paths', sa.JSON(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'dismissed', 'acted', name='lintissuestatus'), nullable=False),
    sa.Column('dismissed_by_id', sa.Integer(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismiss_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dismissed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['lint_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lint_issues_kind'), 'lint_issues', ['kind'], unique=False)
    op.create_index(op.f('ix_lint_issues_report_id'), 'lint_issues', ['report_id'], unique=False)
    op.create_index(op.f('ix_lint_issues_severity'), 'lint_issues', ['severity'], unique=False)
    op.create_index(op.f('ix_lint_issues_status'), 'lint_issues', ['status'], unique=False)
    op.create_table('revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('parent_revision_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'proposed', 'accepted', 'rejected', 'superseded', name='revisionstatus'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisions_author_id'), 'revisions', ['author_id'], unique=False)
    op.create_index(op.f('ix_revisions_page_id'), 'revisions', ['page_id'], unique=False)
    op.create_index(op.f('ix_revisions_status'), 'revisions', ['status'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('anchor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_page_id'), 'comments', ['page_id'], unique=False)
    op.create_index(op.f('ix_comments_revision_id'), 'comments', ['revision_id'], unique=False)
    op.create_table('revision_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('raw_source_id', sa.Integer(), nullable=True),
    sa.Column('ingest_run_id', sa.Integer(), nullable=True),
    sa.Column('edit_id', sa.String(), nullable=True),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('reject_notes', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('source_refs', sa.JSON(), nullable=True),
    sa.Column('conflict_notes', sa.Text(), nullable=True),
    sa.Column('edit_kind', sa.String(), nullable=True),
    sa.Column('is_agent_authored', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_source_id'], ['raw_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_provenance_ingest_run_id'), 'revision_provenance', ['ingest_run_id'], unique=False)
    op.create_index(op.f('ix_revision_provenance_raw_source_id'), 'revision_provenance', ['raw_source_id'], unique=False)
    op.create_index(op.f('ix_revision_provenance_revision_id'), 'revision_provenance', ['revision_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revision_provenance_revision_id'), table_name='revision_provenance')
    op.drop_index(op.f('ix_revision_provenance_raw_source_id'), table_name='revision_provenance')
    op.drop_index(op.f('ix_revision_provenance_ingest_run_id'), table_name='revision_provenance')
    op.drop_table('revision_provenance')
    op.drop_index(op.f('ix_comments_revision_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_page_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_revisions_status'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_page_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_author_id'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_index(op.f('ix_lint_issues_status'), table_name='lint_issues')
    op.drop_index(op.f('ix_lint_issues_severity'), table_name='lint_issues')
    op.drop_index(op.f('ix_lint_issues_report_id'), table_name='lint_issues')
    op.drop_index(op.f('ix_lint_issues_kind'), table_name='lint_issues')
    op.drop_table('lint_issues')
    op.drop_index(op.f('ix_links_target_path'), table_name='links')
    op.drop_index(op.f('ix_links_target_id'), table_name='links')
    op.drop_index(op.f('ix_links_source_id'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_ingest_runs_triggered_by_id'), table_name='ingest_runs')
    op.drop_index(op.f('ix_ingest_runs_status'), table_name='ingest_runs')
    op.drop_index(op.f('ix_ingest_runs_raw_source_id'), table_name='ingest_runs')
    op.drop_table('ingest_runs')
    op.drop_index(op.f('ix_flags_status'), table_name='flags')
    op.drop_index(op.f('ix_flags_page_id'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_chunks_page_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_page_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_artifact_versions_artifact_id'), table_name='artifact_versions')
    op.drop_table('artifact_versions')
    op.drop_index(op.f('ix_artifact_access_log_artifact_id'), table_name='artifact_access_log')
    op.drop_index(op.f('ix_artifact_access_log_accessed_at'), table_name='artifact_access_log')
    op.drop_table('artifact_access_log')
    op.drop_index(op.f('ix_raw_sources_uploaded_by_id'), table_name='raw_sources')
    op.drop_index(op.f('ix_raw_sources_title'), table_name='raw_sources')
    op.drop_index(op.f('ix_raw_sources_ingest_status'), table_name='raw_sources')
    op.drop_table('raw_sources')
    op.drop_index(op.f('ix_pages_path'), table_name='pages')
    op.drop_index(op.f('ix_pages_category_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_lint_reports_triggered_by_id'), table_name='lint_reports')
    op.drop_index(op.f('ix_lint_reports_status'), table_name='lint_reports')
    op.drop_table('lint_reports')
    op.drop_index(op.f('ix_category_editors_user_id'), table_name='category_editors')
    op.drop_index(op.f('ix_category_editors_category_id'), table_name='category_editors')
    op.drop_table('category_editors')
    op.drop_index(op.f('ix_audit_log_target_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_artifacts_short_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_owner_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_users_owner_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
